const currencySymbols = {
    AED: "د.إ", AFN: "؋", XCD: "$", ALL: "L", AMD: "֏", ANG: "ƒ", AOA: "Kz", AQD: "$",
    ARS: "$", AUD: "A$", AZN: "₼", BAM: "KM", BBD: "$", BDT: "৳", XOF: "CFA", BGN: "лв",
    BHD: ".د.ب", BIF: "FBu", BMD: "$", BND: "$", BOB: "Bs", BRL: "R$", BSD: "$", NOK: "kr",
    BWP: "P", BYR: "Br", BZD: "BZ$", CAD: "$", CDF: "FC", XAF: "FCFA", CHF: "CHF", CLP: "$",
    CNY: "¥", COP: "$", CRC: "₡", CUP: "₱", CVE: "$", CYP: "£", CZK: "Kč", DJF: "Fdj",
    DKK: "kr", DOP: "RD$", DZD: "دج", ECS: "$", EEK: "kr", EGP: "£", ETB: "Br", EUR: "€",
    FJD: "$", FKP: "£", GBP: "£", GEL: "₾", GGP: "£", GHS: "₵", GIP: "£", GMD: "D", GNF: "FG",
    GTQ: "Q", GYD: "$", HKD: "$", HNL: "L", HRK: "kn", HTG: "G", HUF: "Ft", IDR: "Rp",
    ILS: "₪", INR: "₹", IQD: "ع.د", IRR: "﷼", ISK: "kr", JMD: "J$", JOD: "د.ا", JPY: "¥",
    KES: "Sh", KGS: "лв", KHR: "៛", KMF: "CF", KPW: "₩", KRW: "₩", KWD: "د.ك", KYD: "$",
    KZT: "₸", LAK: "₭", LBP: "ل.ل", LKR: "Rs", LRD: "$", LSL: "L", LTL: "Lt", LVL: "Ls",
    LYD: "ل.د", MAD: "د.م.", MDL: "L", MGA: "Ar", MKD: "ден", MMK: "K", MNT: "₮", MOP: "P",
    MRO: "UM", MTL: "₤", MUR: "₨", MVR: "Rf", MWK: "MK", MXN: "$", MYR: "RM", MZN: "MT",
    NAD: "$", XPF: "₣", NGN: "₦", NIO: "C$", NPR: "₨", NZD: "NZ$", OMR: "ر.ع.", PAB: "B/.",
    PEN: "S/", PGK: "K", PHP: "₱", PKR: "₨", PLN: "zł", PYG: "₲", QAR: "ر.ق", RON: "lei",
    RSD: "дин", RUB: "₽", RWF: "FRw", SAR: "ر.س", SBD: "$", SCR: "₨", SDG: "ج.س.",
    SEK: "kr", SGD: "$", SKK: "Sk", SLL: "Le", SOS: "Sh", SRD: "$", STD: "Db", SVC: "$",
    SYP: "£", SZL: "L", THB: "฿", TJS: "ЅМ", TMT: "m", TND: "د.ت", TOP: "T$", TRY: "₺",
    TTD: "TT$", TWD: "NT$", TZS: "Sh", UAH: "₴", UGX: "USh", USD: "$", UYU: "$U",
    UZS: "soʻm", VEF: "Bs", VND: "₫", VUV: "Vt", YER: "﷼", ZAR: "R", ZMK: "ZK", ZWD: "Z$"
};
